remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme

logo: https://disesdi.github.io/SusannaCox-StackedTAGLINEV1.png

title: Angles of Attack

description: AI Security Intelligence
